### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by unavailable-888** [Kinuzo/val-triggerbot-in-lua#11]
i followed the steps and its dont not seem to be working is it patched? ඞ.#0758

**Comment by Kinuzo** [comment]
i tested and it's still working
are you using win 10 or 11?

**Comment by unavailable-888** [comment]
win 10

**Comment by unavailable-888** [comment]
i added valorant to game capture before loading the lua like you said

**Comment by unavailable-888** [comment]
![image](https://user-images.githubusercontent.com/93897584/189668399-3e1b646d-8b7e-41de-a244-92d6aed4cf1d.png)

**Comment by Kinuzo** [comment]
ok accept discord.
