### ISSUE TITLE
No action

### ISSUE THREAD

**Issue by kecifej** [Kinuzo/val-triggerbot-in-lua#2]
Not shooting after setting it up.

**Comment by Kinuzo** [comment]
You need to create a valorant game capture scene before loading the script and then set game color to purple.

**Comment by kecifej** [comment]
I obv. did.

**Comment by Kinuzo** [comment]
do you have discord? i can try to help you

**Comment by kecifej** [comment]
I do marijo#0543

**Comment by yacine12345l** [comment]
add me on discord .. Yasser Rabbah#1037
