### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by con-gif** [Kinuzo/val-triggerbot-in-lua#27]
windowed fullscreen mode , purple outline doesnt work. Outdated

**Comment by Kinuzo** [comment]
ur using win 11?

**Comment by con-gif** [comment]
no, win 10

**Comment by Kinuzo** [comment]
have you tried the other fixes?

**Comment by BatturM** [comment]
How can I lower the sensitivity of the aimbot? It's sometimes detecting grey colors as purple.

**Comment by con-gif** [comment]
does it work on win 11 ? I can upgrade if it does

**Comment by Kinuzo** [comment]
some people reported issues with win 11 but it should work
