### ISSUE TITLE
Color Aimbot

### ISSUE THREAD

**Issue by FranklinOP-IND** [Kinuzo/val-triggerbot-in-lua#4]
`Environment.Settings` = {
    SendNotifications = true,
    SaveSettings = true, -- Re-execute upon changing
    ReloadOnTeleport = true,
    Enabled = true,
    TeamCheck = false,
    AliveCheck = true,
    WallCheck = false, -- Laggy
    Sensitivity = 0, -- Animation length (in seconds) before fully locking onto target
    TriggerKey = "MouseButton2",
    Toggle = false,
    LockPart = "Head" -- Body part to lock on
}

`Environment.FOVSettings` = {
    Enabled = true,
    Visible = true,
    Amount = 90,
    Color = "255, 255, 255",
    LockedColor = "255, 70, 70",
    Transparency = 0.5,
    Sides = 60,
    Thickness = 1,
    Filled = false
}

Environment.FOVCircle = Drawing.new("Circle")
Environment.Locked = nil`

can we add like aimbot funcation

**Comment by Kinuzo** [comment]
it's possible but i don't have time rn
