### ISSUE TITLE
Nothing is happening.

### ISSUE THREAD

**Issue by hus7ler** [Kinuzo/val-triggerbot-in-lua#6]
Game color: Purple (Tritanopia)
I have the game capture on valorant.
I play windowed fullscreen.
My triggerbot is binded on M4. (Tried M5 also, still doesn't work).
![image](https://user-images.githubusercontent.com/112317542/187067964-9259bea9-6a76-485d-90f3-3d01cad45c9f.png)

**Comment by Kinuzo** [comment]
do you have discord?

**Comment by hus7ler** [comment]
yep hustler.#8225

**Comment by Kinuzo** [comment]
nice
